version: '3'
services:
  postgres:
    image: postgres:13.9-alpine
    environment:
      - POSTGRES_DB=backstage
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
  backstage:
    build: 
      context: .
      dockerfile: './packages/backend/Dockerfile'
    ports:
      - 7007:7007
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage123
      - AUTH_GITHUB_CLIENT_ID = 2b28145f2873f62cda86
      - AUTH_GITHUB_CLIENT_SECRET = 0e0a1cc62ddef67aa4c05f5975c59c706585e92b
volumes:
  postgres_data: