apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  AUTH_GITHUB_CLIENT_ID: MmIyODE0NWYyODczZjYyY2RhODY=
  AUTH_GITHUB_CLIENT_SECRET: MGUwYTFjYzYyZGRlZjY3YWE0YzA1ZjU5NzVjNTljNzA2NTg1ZTkyYg==
  GITHUB_TOKEN: Z2hwX1N0dEhTM0ZpdG9QSlpDOFhEZXhIb0VjN0dheVF1cDFOdXZhRQ==
  