apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
  labels:
    app: postgres
  namespace: backstage
spec:
  storageClassName: efs-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05b8074b549733425
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
  namespace: backstage
  labels:
    app: postgres
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi